name: product_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  equatable: ^2.0.5

  # HTTP client
  dio: ^5.1.2
  pretty_dio_logger: ^1.2.0

  # Dependency Injection
  get_it: ^7.6.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # JSON serialization
  json_annotation: ^4.9.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
